### ISSUE TITLE
Integrate new generated DTO dataclasses with API fetching

### ISSUE THREAD

**Issue by lmmx** [lmmx/tubeulator#10]
The API fetching is somewhat set up (?) via the `tubeulator.fetch` interface. These next need to be connected up to the DTOs which consume the response they receive.

For example, the `/Line/Meta/Modes` endpoint can be accessed via `tubeulator.fetch.line.meta_modes` (fetch is a generic object of interfaces, i.e. `EndpointInfo` objects from `tubeulator.api.interface`, and the 'routes' on the endpoint are each a `Request` object from `tubeulator.api.request` with overriden call dunder method) and the info about the endpoint is stored in the `path` attribute

```py
>>> type(tubeulator.fetch.line)
<class 'tubeulator.api.interface.EndpointInfo'>
>>> type(tubeulator.fetch.line.meta_modes)
<class 'tubeulator.api.request.Request'>
>>> tubeulator.fetch.line.meta_modes.path.endpoint.name
'LINE'
>>> tubeulator.fetch.line.meta_modes.path.endpoint.value
'Line'
>>> tubeulator.fetch.line.meta_modes.path.route.value
'/Meta/Modes'
```

So we have the:
- schema name (`tubeulator.fetch.line.meta_modes.path.endpoint.value`)
- route name (`tubeulator.fetch.line.meta_modes.path.route.value`)

Therefore we can retrieve the return type from our schema:

- Get the schema by schema name (`load_endpoint_schema`)
- Get the route from the schema's routes (under the "paths" key)

```py
>>> schema = tubeulator.utils.paths.load_endpoint_schema("Line")
>>> schema["paths"]["/Meta/Modes"]
{'get': {'tags': ['Line'],
         'summary': 'Gets a list of valid modes',
         'description': 'Gets a list of valid modes',
         'operationId': 'Line_MetaModes',
         'responses': {'200': {'description': 'OK',
                               'content': {'application/json': {'schema': {'$ref': '#/components/schemas/MetaModesGet200ApplicationJsonResponse'},
                                                                'example': [{'isTflService': True,
                                                                             'isFarePaying': True,
                                                                             'isScheduledService': True,
                                                                             'modeName': 'string'}]},
...
```

Note that I already established we always use `GET` so we can hardcode that assumption.

```py
>>> route_info = schema["paths"]["/Meta/Modes"]
>>> response_info = route_info["get"]["responses"]["200"]["content"]["application/json"]
{'schema': {'$ref': '#/components/schemas/MetaModesGet200ApplicationJsonResponse'},
 'example': [{'isTflService': True,
              'isFarePaying': True,
              'isScheduledService': True,
              'modeName': 'string'}]}
```

From this we can extract both a schema and a sample of the JSON we should expect to be able to parse (i.e. the form but not the content). It's therefore testable offline.

**Comment by lmmx** [comment]
Implemented a way to do it using an enum and some string handling to ensure a Python enum friendly key is used:

```py
>>> from tubeulator.codegen import load_test
>>> component_name = "MetaModesGet200ApplicationJsonResponse"
>>> deserialiser = load_test.Line.Deserialisers.select_component(component_name).value
>>> deserialiser
<class 'tubeulator.generated.Line.MetaModesGet200ApplicationJsonResponse'>
```

This may not have been a great choice to demo because... it has no attributes

**Comment by lmmx** [comment]
Now it's been shown that, in one simple case (presumably in all), we can integrate the fetching and DTO parsing.

The site of retrieval is the place (the neat `fetch` setup) is where we want to add the connectivity through to the DTOs.

This means that we want to:

- add a `parse` method to be run after `fetch` (so that we return internal DTO types not the raw unparsed JSON)
- connect the `parse` method to the appropriate DTO by retrieving the return type of the endpoint route
  - potentially parse directly with `from_dict` for an object type response
  - potentially parse by reference using the `$ref` component's DTO for an array-type response

**Comment by lmmx** [comment]
I considered putting the parsing directly in with the Request but I think that's incorrect structure

```diff
--- a/src/tubeulator/api/request.py
+++ b/src/tubeulator/api/request.py
@@ -7,6 +7,7 @@ from urllib.parse import urlencode
 import httpx
 
 from ..db.store_creds import check_creds
+from ..utils.paths import SchemaPath
 from .endpoint.names import EndpointNames
 from .endpoint.routes.types import AnyEndpointRouteEnum
 
@@ -93,13 +94,20 @@ class Request:
     path: Path
 
     def __call__(self, *args, **kwargs):
-        return self.send(*args, **kwargs)
+        result = self.send(*args, **kwargs)
+        return result
 
     def send(self, *args, **kwargs):
         url = self.path.build_url(*args, **kwargs)
         response = GET(url=url)
         response.raise_for_status()
-        return response.json()
+        return response.content
+
+    # def parse(self, json: str):
+    #     component_schema = find_schema_by_name
+    #     dto_ref = SchemaPath(component_schema)
+    #     parsed = dto.from_json(json)
+    #     return parsed
```

The reason I went to put it there is because of the central role of the `Request` object. In fact we probably want to build on top of the `Request` object rather than making it a 'god class'.

**Comment by lmmx** [comment]
Very close but the validation raises

```py
>>> tubeulator.fetch.line.meta_modes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/louis/dev/tubeulator/src/tubeulator/api/request.py", line 99, in __call__
    parsed = self.parse(result.content)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/dev/tubeulator/src/tubeulator/api/request.py", line 125, in parse
    parsed = dto.from_json(json)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/tubeulator/lib/python3.11/site-packages/dataclass_wizard/serial_json.py", line 48, in from_json
    return fromdict(cls, o) if isinstance(o, dict) else fromlist(cls, o)
                                                        ^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/tubeulator/lib/python3.11/site-packages/dataclass_wizard/loaders.py", line 552, in fromlist
    return [load(d) for d in list_of_dict]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/tubeulator/lib/python3.11/site-packages/dataclass_wizard/loaders.py", line 552, in <listcomp>
    return [load(d) for d in list_of_dict]
            ^^^^^^^
  File "/home/louis/miniconda3/envs/tubeulator/lib/python3.11/site-packages/dataclass_wizard/loaders.py", line 611, in cls_fromdict
    field_name = lookup_field_for_json_key(o, json_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/louis/miniconda3/envs/tubeulator/lib/python3.11/site-packages/dataclass_wizard/loaders.py", line 705, in lookup_field_for_json_key
    raise e from None
dataclass_wizard.errors.UnknownJSONKey: A JSON key is missing from the dataclass schema for class `MetaModesGet200ApplicationJsonResponse`.
  unknown key: '$type'
  dataclass fields: ['_source_schema_name', '_component_schema_name']
  input JSON object: {"$type": "Tfl.Api.Presentation.Entities.Mode, Tfl.Api.Presentation.Entities", "isTflService": true, "isFarePaying": true, "isScheduledService": true, "modeName": "bus"}
```

**Comment by lmmx** [comment]
I tried commenting out the `raise_on_unknown_json_key` and the resulting example call gave a bunch of non-results...

```py
>>> tubeulator.fetch.line.meta_modes()[1]
MetaModesGet200ApplicationJsonResponse(_source_schema_name='Line', _component_schema_name='MetaModesGet200ApplicationJsonResponse')
```

There's no info in these, just the default values from the DTO classdef

**Comment by lmmx** [comment]
This now reproduces

```py
>>> import tubeulator                                                                
>>> resp = tubeulator.fetch.line.meta_modes()                                       
                                          
>>>                                                                                                                                                                      
>>> from pprint import pprint                                                                                                                                            
>>> pprint(resp)                    
[Mode(IsTflService=True,                                                                                                                                                 
      IsFarePaying=True,           
      IsScheduledService=True,     
      ModeName='bus',                                                               
      _source_schema_name='Line',
      _component_schema_name='Tfl'),                                                
 Mode(IsTflService=True,                                                            
      IsFarePaying=True,              
      IsScheduledService=True,    
      ModeName='cable-car',          
      _source_schema_name='Line',                                                   
      _component_schema_name='Tfl'),
 Mode(IsTflService=False,                                                           
      IsFarePaying=True,                                                            
      IsScheduledService=True,                                                                                                                                           
      ModeName='coach',               
      _source_schema_name='Line',                                                                                                                                        
      _component_schema_name='Tfl'),  
...
```

**Comment by lmmx** [comment]
DTOs now parse after fetching but the appearance of `Any` implicitly in `dict` types is due to not specifying nested structure.

For instance, for `passengerFlows` in `Tfl-5` in `StopPoint`

```py
            "Tfl-5": {
                "type": "object",
                "properties": {
                    "passengerFlows": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Tfl-3"
                        },
                        "description": "Busiest times at a station (static information)"
                    },
                    "trainLoadings": {
                        "type": "array",
                        "items": {
                            "$ref": "#/components/schemas/Tfl-4"
                        },
                        "description": "Train Loading on a scale 1-6, 1 being \"Very quiet\" and 6 being \"Exceptionally busy\" (static information)"
                    }
                }
            },
```
